improve support for multi-file build

diff --git a/scripts/g++-32.in b/scripts/g++-32.in
--- a/scripts/g++-32.in
+++ b/scripts/g++-32.in
@@ -33,12 +33,21 @@ then
     exec "${EJUDGE_BUILD_SCRIPT}" $@
 fi
 
-[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-Wall -O2"
-[ x"${EJUDGE_LIBS}" = x ] && EJUDGE_LIBS="-lm"
+[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-O2"
 
 unset LANG
 unset LC_ALL
 unset LC_MESSAGES
 unset LANGUAGE
 
-exec "${GPPRUN}" ${EJUDGE_FLAGS} -m32 "$1" -o "$2" ${EJUDGE_LIBS}
+if [ "${EJUDGE_SOLUTION_FILE}" != "" ]
+then
+    if ! mv "$1" "${EJUDGE_SOLUTION_FILE}.cpp"
+    then
+        echo "failed to rename ${1} to ${EJUDGE_SOLUTION_FILE}.cpp" >&2
+        exit 1
+    fi
+    exec "${GPPRUN}" -m32 ${EJUDGE_FLAGS} *.cpp -o "$2" ${EJUDGE_LIBS}
+fi
+
+exec "${GPPRUN}" -m32 ${EJUDGE_FLAGS} "$1" -o "$2" ${EJUDGE_LIBS}
diff --git a/scripts/g++-vg.in b/scripts/g++-vg.in
--- a/scripts/g++-vg.in
+++ b/scripts/g++-vg.in
@@ -34,11 +34,20 @@ then
 fi
 
 [ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-O2 -g"
-[ x"${EJUDGE_LIBS}" = x ] && EJUDGE_LIBS="-lm"
 
 unset LANG
 unset LC_ALL
 unset LC_MESSAGES
 unset LANGUAGE
+
+if [ "${EJUDGE_SOLUTION_FILE}" != "" ]
+then
+    if ! mv "$1" "${EJUDGE_SOLUTION_FILE}.cpp"
+    then
+        echo "failed to rename ${1} to ${EJUDGE_SOLUTION_FILE}.cpp" >&2
+        exit 1
+    fi
+    exec "${GPPRUN}" ${EJUDGE_FLAGS} *.cpp -o "$2" ${EJUDGE_LIBS}
+fi
 
 exec "${GPPRUN}" ${EJUDGE_FLAGS} "$1" -o "$2" ${EJUDGE_LIBS}
diff --git a/scripts/g++.in b/scripts/g++.in
--- a/scripts/g++.in
+++ b/scripts/g++.in
@@ -33,25 +33,21 @@ then
     exec "${EJUDGE_BUILD_SCRIPT}" $@
 fi
 
-[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-Wall -O2"
-#[ x"${EJUDGE_LIBS}" = x ] && EJUDGE_LIBS="-lm"
+[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-O2"
 
 unset LANG
 unset LC_ALL
 unset LC_MESSAGES
 unset LANGUAGE
 
-if [ "${EJUDGE_COMPILE_MASK}" != "" ]
+if [ "${EJUDGE_SOLUTION_FILE}" != "" ]
 then
-    if [ "${EJUDGE_SOLUTION_FILE}" != "" ]
+    if ! mv "$1" "${EJUDGE_SOLUTION_FILE}.cpp"
     then
-        if ! mv "$1" "${EJUDGE_SOLUTION_FILE}.cpp"
-        then
-            echo "failed to rename $1 to $EJUDGE_SOLUTION_FILE" >&2
-            exit 1
-        fi
-        exec "${GPPRUN}" ${EJUDGE_FLAGS} ${EJUDGE_COMPILE_MASK} -o "$2" -lm ${EJUDGE_LIBS}
+        echo "failed to rename ${1} to ${EJUDGE_SOLUTION_FILE}.cpp" >&2
+        exit 1
     fi
+    exec "${GPPRUN}" ${EJUDGE_FLAGS} *.cpp -o "$2" ${EJUDGE_LIBS}
 fi
 
 exec "${GPPRUN}" ${EJUDGE_FLAGS} "$1" -o "$2" -lm ${EJUDGE_LIBS}
diff --git a/scripts/gcc-32.in b/scripts/gcc-32.in
--- a/scripts/gcc-32.in
+++ b/scripts/gcc-32.in
@@ -33,7 +33,7 @@ then
     exec "${EJUDGE_BUILD_SCRIPT}" $@
 fi
 
-[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-Wall -O2"
+[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-O2"
 [ x"${EJUDGE_LIBS}" = x ] && EJUDGE_LIBS="-lm"
 
 unset LANG
@@ -41,4 +41,14 @@ unset LC_ALL
 unset LC_MESSAGES
 unset LANGUAGE
 
-exec "${GCCRUN}" ${EJUDGE_FLAGS} -m32 "$1" -o "$2" ${EJUDGE_LIBS}
+if [ "${EJUDGE_SOLUTION_FILE}" != "" ]
+then
+    if ! mv "$1" "${EJUDGE_SOLUTION_FILE}.c"
+    then
+        echo "failed to rename ${1} to ${EJUDGE_SOLUTION_FILE}.c" >&2
+        exit 1
+    fi
+    exec "${GCCRUN}" ${EJUDGE_FLAGS} *.c -o "$2" ${EJUDGE_LIBS}
+fi
+
+exec "${GCCRUN}" -m32 ${EJUDGE_FLAGS} "$1" -o "$2" ${EJUDGE_LIBS}
diff --git a/scripts/gcc.in b/scripts/gcc.in
--- a/scripts/gcc.in
+++ b/scripts/gcc.in
@@ -33,12 +33,22 @@ then
     exec "${EJUDGE_BUILD_SCRIPT}" $@
 fi
 
-[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-Wall -O2"
+[ x"${EJUDGE_FLAGS}" = x ] && EJUDGE_FLAGS="-O2"
 [ x"${EJUDGE_LIBS}" = x ] && EJUDGE_LIBS="-lm"
 
 unset LANG
 unset LC_ALL
 unset LC_MESSAGES
 unset LANGUAGE
+
+if [ "${EJUDGE_SOLUTION_FILE}" != "" ]
+then
+    if ! mv "$1" "${EJUDGE_SOLUTION_FILE}.c"
+    then
+        echo "failed to rename ${1} to ${EJUDGE_SOLUTION_FILE}.c" >&2
+        exit 1
+    fi
+    exec "${GCCRUN}" ${EJUDGE_FLAGS} *.c -o "$2" ${EJUDGE_LIBS}
+fi
 
 exec "${GCCRUN}" ${EJUDGE_FLAGS} "$1" -o "$2" ${EJUDGE_LIBS}
diff --git a/scripts/javac.in b/scripts/javac.in
--- a/scripts/javac.in
+++ b/scripts/javac.in
@@ -49,6 +49,55 @@ then
     export PATH
 fi
 
+D=`dirname "${JAVARUN}"`
+if [ "$D" = "." ]
+then
+    JARRUN=jar
+else
+    JARRUN="${D}/jar"
+fi
+
+solution_file=""
+if [ "${EJUDGE_SOLUTION_FILE_JAVA}" != "" ]
+then
+    solution_file="${EJUDGE_SOLUTION_FILE_JAVA}"
+elif [ "${EJUDGE_SOLUTION_FILE}" != "" ]
+    solution_file="${EJUDGE_SOLUTION_FILE}"
+fi
+start_file=""
+if [ "${EJUDGE_START_FILE_JAVA}" != "" ]
+then
+    start_file="${EJUDGE_START_FILE_JAVA}"
+elif [ "${EJUDGE_START_FILE}" != "" ]
+    start_file="${EJUDGE_START_FILE}"
+fi
+
+if [ "${solution_file}" != "" -a "${start_file}" != "" ]
+then
+    if ! mv "${infile}" "${solution_file}.java"
+    then
+        echo "failed to rename source file" >&2
+        exit 1
+    fi
+
+    CPOPT=
+    if [ "${EJUDGE_CLASSPATH}" != "" ]
+    then
+        CPOPT=" -cp ${EJUDGE_CLASSPATH} "
+    fi
+
+    "${JAVACRUN}" --target "${JAVAVER}" ${CPOPT} *.java || exit 1
+
+    MOPT=
+    if [ "${EJUDGE_CLASSPATH}" != "" ]
+    then
+        echo "Class-Path: ${EJUDGE_CLASSPATH}" > manifest.txt
+        MOPT=" -m manifest.txt "
+    fi
+
+    exec "${JARRUN}" -c -f "${outfile}" ${MOPT} -e "${start_file}" *.class
+fi
+
 rm -f *.class
 
 JAVA_CLASSNAME="${libexecdir}/ejudge/lang/java-classname.jar"
@@ -86,14 +135,6 @@ then
 fi
 
 "${JAVACRUN}" --target "${JAVAVER}" ${CPOPT} *.java || exit 1
-
-D=`dirname "${JAVARUN}"`
-if [ "$D" = "." ]
-then
-    JARRUN=jar
-else
-    JARRUN="${D}/jar"
-fi
 
 MOPT=
 if [ "${EJUDGE_CLASSPATH}" != "" ]
